name: CI linter workflow

on:
  [pull_request, push]
  # pull_request:
  #   branches: [dev]
  # push:
  #   branches: [dev]

  # Allows you to run this workflow manually from the Actions tab
# workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
        
    steps:
      - uses: actions/checkout@v4
      # - uses: actions/setup-node@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff check
      
      - name: Run Ruff linter
        run: |
          ruff .

      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt



    #         build:
    # runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     python-version: [3.8]

    # steps:
    #   - uses: actions/checkout@v2
    #   - name: Set up Python ${{ matrix.python-version }}
    #     uses: actions/setup-python@v1
    #     with:
    #       python-version: ${{ matrix.python-version }}
    #   - name: Install dependencies
    #     run: |
    #       python -m pip install --upgrade pip
    #       pip install -r requirements.txt
    #   - name: Test with pytest
    #     run: |
    #       pip install pytest
    #       python -m pytest